package com.cursodegit.twitterFeed;

import java.util.HashMap;

public class ConnectionMock extends ConnectionA {
	
	public ConnectionMock(String oAuthConsumerKey, String oAuthConsumerSecret) throws ConnectionException {
	}
	
	public String get(String uri) throws ConnectionException {
		return "[\r\n"
				+ "  {\r\n"
				+ "    \"created_at\": \"Tue Jul 13 21:43:20 +0000 2021\",\r\n"
				+ "    \"id\": 1415064325295943700,\r\n"
				+ "    \"id_str\": \"1415064325295943680\",\r\n"
				+ "    \"text\": \"I've just opened a subscription form for those who want to get notify by email when I post in my blog.\\n\\nhttps://t.co/NyQPLySO8M\",\r\n"
				+ "    \"truncated\": false,\r\n"
				+ "    \"entities\": {\r\n"
				+ "      \"hashtags\": [],\r\n"
				+ "      \"symbols\": [],\r\n"
				+ "      \"user_mentions\": [],\r\n"
				+ "      \"urls\": [\r\n"
				+ "        {\r\n"
				+ "          \"url\": \"https://t.co/NyQPLySO8M\",\r\n"
				+ "          \"expanded_url\": \"https://sendfox.com/alfonsoalba\",\r\n"
				+ "          \"display_url\": \"sendfox.com/alfonsoalba\",\r\n"
				+ "          \"indices\": [\r\n"
				+ "            104,\r\n"
				+ "            127\r\n"
				+ "          ]\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    \"source\": \"<a href=\\\"https://mobile.twitter.com\\\" rel=\\\"nofollow\\\">Twitter Web App</a>\",\r\n"
				+ "    \"in_reply_to_status_id\": null,\r\n"
				+ "    \"in_reply_to_status_id_str\": null,\r\n"
				+ "    \"in_reply_to_user_id\": null,\r\n"
				+ "    \"in_reply_to_user_id_str\": null,\r\n"
				+ "    \"in_reply_to_screen_name\": null,\r\n"
				+ "    \"user\": {\r\n"
				+ "      \"id\": 59133365,\r\n"
				+ "      \"id_str\": \"59133365\"\r\n"
				+ "    },\r\n"
				+ "    \"geo\": null,\r\n"
				+ "    \"coordinates\": null,\r\n"
				+ "    \"place\": null,\r\n"
				+ "    \"contributors\": null,\r\n"
				+ "    \"is_quote_status\": false,\r\n"
				+ "    \"retweet_count\": 0,\r\n"
				+ "    \"favorite_count\": 3,\r\n"
				+ "    \"favorited\": false,\r\n"
				+ "    \"retweeted\": false,\r\n"
				+ "    \"possibly_sensitive\": false,\r\n"
				+ "    \"lang\": \"en\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"created_at\": \"Mon Jun 28 07:26:31 +0000 2021\",\r\n"
				+ "    \"id\": 1409412882396336000,\r\n"
				+ "    \"id_str\": \"1409412882396336128\",\r\n"
				+ "    \"text\": \"I've just publish a new post about how I'm using #CloudRun  from #gcloud to host the website… https://t.co/iICVGuafoR\",\r\n"
				+ "    \"truncated\": true,\r\n"
				+ "    \"entities\": {\r\n"
				+ "      \"hashtags\": [\r\n"
				+ "        {\r\n"
				+ "          \"text\": \"CloudRun\",\r\n"
				+ "          \"indices\": [\r\n"
				+ "            49,\r\n"
				+ "            58\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "          \"text\": \"gcloud\",\r\n"
				+ "          \"indices\": [\r\n"
				+ "            65,\r\n"
				+ "            72\r\n"
				+ "          ]\r\n"
				+ "        }\r\n"
				+ "      ],\r\n"
				+ "      \"symbols\": [],\r\n"
				+ "      \"user_mentions\": [],\r\n"
				+ "      \"urls\": [\r\n"
				+ "        {\r\n"
				+ "          \"url\": \"https://t.co/iICVGuafoR\",\r\n"
				+ "          \"expanded_url\": \"https://twitter.com/i/web/status/1409412882396336128\",\r\n"
				+ "          \"display_url\": \"twitter.com/i/web/status/1…\",\r\n"
				+ "          \"indices\": [\r\n"
				+ "            94,\r\n"
				+ "            117\r\n"
				+ "          ]\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    \"source\": \"<a href=\\\"https://publer.io\\\" rel=\\\"nofollow\\\">Publer.io</a>\",\r\n"
				+ "    \"in_reply_to_status_id\": null,\r\n"
				+ "    \"in_reply_to_status_id_str\": null,\r\n"
				+ "    \"in_reply_to_user_id\": null,\r\n"
				+ "    \"in_reply_to_user_id_str\": null,\r\n"
				+ "    \"in_reply_to_screen_name\": null,\r\n"
				+ "    \"user\": {\r\n"
				+ "      \"id\": 59133365,\r\n"
				+ "      \"id_str\": \"59133365\"\r\n"
				+ "    },\r\n"
				+ "    \"geo\": null,\r\n"
				+ "    \"coordinates\": null,\r\n"
				+ "    \"place\": {\r\n"
				+ "      \"id\": \"ea520f3528c9b3e4\",\r\n"
				+ "      \"url\": \"https://api.twitter.com/1.1/geo/id/ea520f3528c9b3e4.json\",\r\n"
				+ "      \"place_type\": \"admin\",\r\n"
				+ "      \"name\": \"Madrid\",\r\n"
				+ "      \"full_name\": \"Madrid, Comunidad de Madrid\",\r\n"
				+ "      \"country_code\": \"ES\",\r\n"
				+ "      \"country\": \"España\",\r\n"
				+ "      \"contained_within\": [],\r\n"
				+ "      \"bounding_box\": {\r\n"
				+ "        \"type\": \"Polygon\",\r\n"
				+ "        \"coordinates\": [\r\n"
				+ "          [\r\n"
				+ "            [\r\n"
				+ "              -4.5791745,\r\n"
				+ "              39.8845366\r\n"
				+ "            ],\r\n"
				+ "            [\r\n"
				+ "              -3.0531322,\r\n"
				+ "              39.8845366\r\n"
				+ "            ],\r\n"
				+ "            [\r\n"
				+ "              -3.0531322,\r\n"
				+ "              41.1649106\r\n"
				+ "            ],\r\n"
				+ "            [\r\n"
				+ "              -4.5791745,\r\n"
				+ "              41.1649106\r\n"
				+ "            ]\r\n"
				+ "          ]\r\n"
				+ "        ]\r\n"
				+ "      },\r\n"
				+ "      \"attributes\": {}\r\n"
				+ "    },\r\n"
				+ "    \"contributors\": null,\r\n"
				+ "    \"is_quote_status\": false,\r\n"
				+ "    \"retweet_count\": 0,\r\n"
				+ "    \"favorite_count\": 1,\r\n"
				+ "    \"favorited\": false,\r\n"
				+ "    \"retweeted\": false,\r\n"
				+ "    \"possibly_sensitive\": false,\r\n"
				+ "    \"lang\": \"en\"\r\n"
				+ "  }\r\n"
				+ "]";
	}
}
